Class FEDCPromoXaml
{
    Static [String] $Content = @(
    '<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
    '        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
    '        Title="[FightingEntropy]://Domain Controller Promotion"',
    '        Width="550"',
    '        Height="450"',
    '        Topmost="True"',
    '        ResizeMode="NoResize"',
    '        Icon="C:\ProgramData\Secure Digits Plus LLC\FightingEntropy\2022.12.0\Graphics\icon.ico"',
    '        HorizontalAlignment="Center"',
    '        WindowStartupLocation="CenterScreen">',
    '    <Window.Resources>',
    '        <Style x:Key="DropShadow">',
    '            <Setter Property="TextBlock.Effect">',
    '                <Setter.Value>',
    '                    <DropShadowEffect ShadowDepth="1"/>',
    '                </Setter.Value>',
    '            </Setter>',
    '        </Style>',
    '        <Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource DropShadow}">',
    '            <Setter Property="TextBlock.TextAlignment" Value="Left"/>',
    '            <Setter Property="VerticalContentAlignment" Value="Center"/>',
    '            <Setter Property="HorizontalContentAlignment" Value="Left"/>',
    '            <Setter Property="Height" Value="24"/>',
    '            <Setter Property="Margin" Value="4"/>',
    '            <Setter Property="FontSize" Value="12"/>',
    '            <Setter Property="Foreground" Value="#000000"/>',
    '            <Setter Property="TextWrapping" Value="Wrap"/>',
    '            <Style.Resources>',
    '                <Style TargetType="Border">',
    '                    <Setter Property="CornerRadius" Value="2"/>',
    '                </Style>',
    '            </Style.Resources>',
    '        </Style>',
    '        <Style TargetType="{x:Type PasswordBox}" BasedOn="{StaticResource DropShadow}">',
    '            <Setter Property="TextBlock.TextAlignment" Value="Left"/>',
    '            <Setter Property="VerticalContentAlignment" Value="Center"/>',
    '            <Setter Property="HorizontalContentAlignment" Value="Left"/>',
    '            <Setter Property="Margin" Value="4"/>',
    '            <Setter Property="Height" Value="24"/>',
    '        </Style>',
    '        <Style TargetType="CheckBox">',
    '            <Setter Property="VerticalContentAlignment" Value="Center"/>',
    '            <Setter Property="Height" Value="24"/>',
    '            <Setter Property="Margin" Value="5"/>',
    '        </Style>',
    '        <Style TargetType="ToolTip">',
    '            <Setter Property="Background" Value="#000000"/>',
    '            <Setter Property="Foreground" Value="#66D066"/>',
    '        </Style>',
    '        <Style TargetType="TabItem">',
    '            <Setter Property="Template">',
    '                <Setter.Value>',
    '                    <ControlTemplate TargetType="TabItem">',
    '                        <Border Name="Border"',
    '                                BorderThickness="2"',
    '                                BorderBrush="Black"',
    '                                CornerRadius="2"',
    '                                Margin="2">',
    '                            <ContentPresenter x:Name="ContentSite"',
    '                                              VerticalAlignment="Center"',
    '                                              HorizontalAlignment="Right"',
    '                                              ContentSource="Header"',
    '                                              Margin="5"/>',
    '                        </Border>',
    '                        <ControlTemplate.Triggers>',
    '                            <Trigger Property="IsSelected" Value="True">',
    '                                <Setter TargetName="Border"',
    '                                        Property="Background" ',
    '                                        Value="#4444FF"/>',
    '                                <Setter Property="Foreground"',
    '                                        Value="#FFFFFF"/>',
    '                            </Trigger>',
    '                            <Trigger Property="IsSelected" Value="False">',
    '                                <Setter TargetName="Border"',
    '                                        Property="Background" ',
    '                                        Value="#DFFFBA"/>',
    '                                <Setter Property="Foreground" ',
    '                                        Value="#000000"/>',
    '                            </Trigger>',
    '                            <Trigger Property="IsEnabled" Value="False">',
    '                                <Setter TargetName="Border"',
    '                                        Property="Background"',
    '                                        Value="#6F6F6F"/>',
    '                                <Setter Property="Foreground"',
    '                                        Value="#9F9F9F"/>',
    '                            </Trigger>',
    '                        </ControlTemplate.Triggers>',
    '                    </ControlTemplate>',
    '                </Setter.Value>',
    '            </Setter>',
    '        </Style>',
    '        <Style TargetType="Button">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="Padding" Value="5"/>',
    '            <Setter Property="Height" Value="30"/>',
    '            <Setter Property="FontWeight" Value="Semibold"/>',
    '            <Setter Property="FontSize" Value="12"/>',
    '            <Setter Property="Foreground" Value="Black"/>',
    '            <Setter Property="Background" Value="#DFFFBA"/>',
    '            <Setter Property="BorderThickness" Value="2"/>',
    '            <Setter Property="VerticalContentAlignment" Value="Center"/>',
    '            <Style.Resources>',
    '                <Style TargetType="Border">',
    '                    <Setter Property="CornerRadius" Value="5"/>',
    '                </Style>',
    '            </Style.Resources>',
    '        </Style>',
    '        <Style TargetType="ComboBox">',
    '            <Setter Property="Height" Value="24"/>',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="FontSize" Value="12"/>',
    '            <Setter Property="FontWeight" Value="Normal"/>',
    '        </Style>',
    '        <Style TargetType="TabControl">',
    '            <Setter Property="TabStripPlacement" Value="Top"/>',
    '            <Setter Property="HorizontalContentAlignment" Value="Center"/>',
    '            <Setter Property="Background" Value="LightYellow"/>',
    '        </Style>',
    '        <Style TargetType="GroupBox">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="Padding" Value="5"/>',
    '            <Setter Property="BorderThickness" Value="2"/>',
    '            <Setter Property="BorderBrush" Value="Black"/>',
    '            <Setter Property="Foreground" Value="Black"/>',
    '        </Style>',
    '        <Style TargetType="TextBox" x:Key="Block">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="Padding" Value="5"/>',
    '            <Setter Property="FontFamily" Value="Consolas"/>',
    '            <Setter Property="Height" Value="180"/>',
    '            <Setter Property="FontSize" Value="10"/>',
    '            <Setter Property="FontWeight" Value="Normal"/>',
    '            <Setter Property="AcceptsReturn" Value="True"/>',
    '            <Setter Property="VerticalAlignment" Value="Top"/>',
    '            <Setter Property="TextAlignment" Value="Left"/>',
    '            <Setter Property="VerticalContentAlignment" Value="Top"/>',
    '            <Setter Property="VerticalScrollBarVisibility" Value="Visible"/>',
    '            <Setter Property="TextBlock.Effect">',
    '                <Setter.Value>',
    '                    <DropShadowEffect ShadowDepth="1"/>',
    '                </Setter.Value>',
    '            </Setter>',
    '        </Style>',
    '        <Style TargetType="DataGrid">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="AutoGenerateColumns" Value="False"/>',
    '            <Setter Property="AlternationCount" Value="3"/>',
    '            <Setter Property="HeadersVisibility" Value="Column"/>',
    '            <Setter Property="CanUserResizeRows" Value="False"/>',
    '            <Setter Property="CanUserAddRows" Value="False"/>',
    '            <Setter Property="IsReadOnly" Value="True"/>',
    '            <Setter Property="IsTabStop" Value="True"/>',
    '            <Setter Property="IsTextSearchEnabled" Value="True"/>',
    '            <Setter Property="SelectionMode" Value="Extended"/>',
    '            <Setter Property="ScrollViewer.CanContentScroll" Value="True"/>',
    '            <Setter Property="ScrollViewer.VerticalScrollBarVisibility" Value="Auto"/>',
    '            <Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Auto"/>',
    '        </Style>',
    '        <Style TargetType="DataGridRow">',
    '            <Setter Property="BorderBrush" Value="Black"/>',
    '        </Style>',
    '        <Style TargetType="DataGridColumnHeader">',
    '            <Setter Property="FontSize"   Value="8"/>',
    '            <Setter Property="FontWeight" Value="Medium"/>',
    '            <Setter Property="Margin" Value="2"/>',
    '            <Setter Property="Padding" Value="2"/>',
    '        </Style>',
    '        <Style TargetType="Label">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="FontWeight" Value="Bold"/>',
    '            <Setter Property="Background" Value="Black"/>',
    '            <Setter Property="Foreground" Value="White"/>',
    '            <Setter Property="BorderBrush" Value="Gray"/>',
    '            <Setter Property="BorderThickness" Value="2"/>',
    '            <Style.Resources>',
    '                <Style TargetType="Border">',
    '                    <Setter Property="CornerRadius" Value="5"/>',
    '                </Style>',
    '            </Style.Resources>',
    '        </Style>',
    '        <Style x:Key="LabelGray" TargetType="Label">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="FontWeight" Value="Bold"/>',
    '            <Setter Property="Background" Value="DarkSlateGray"/>',
    '            <Setter Property="Foreground" Value="White"/>',
    '            <Setter Property="BorderBrush" Value="Black"/>',
    '            <Setter Property="BorderThickness" Value="2"/>',
    '            <Setter Property="HorizontalContentAlignment" Value="Center"/>',
    '            <Style.Resources>',
    '                <Style TargetType="Border">',
    '                    <Setter Property="CornerRadius" Value="5"/>',
    '                </Style>',
    '            </Style.Resources>',
    '        </Style>',
    '        <Style x:Key="LabelRed" TargetType="Label">',
    '            <Setter Property="Margin" Value="5"/>',
    '            <Setter Property="FontWeight" Value="Bold"/>',
    '            <Setter Property="Background" Value="IndianRed"/>',
    '            <Setter Property="Foreground" Value="White"/>',
    '            <Setter Property="BorderBrush" Value="Black"/>',
    '            <Setter Property="BorderThickness" Value="2"/>',
    '            <Setter Property="HorizontalContentAlignment" Value="Left"/>',
    '            <Style.Resources>',
    '                <Style TargetType="Border">',
    '                    <Setter Property="CornerRadius" Value="5"/>',
    '                </Style>',
    '            </Style.Resources>',
    '        </Style>',
    '        <Style x:Key="Line" TargetType="Border">',
    '            <Setter Property="Background" Value="Black"/>',
    '            <Setter Property="BorderThickness" Value="0"/>',
    '            <Setter Property="Margin" Value="4"/>',
    '        </Style>',
    '    </Window.Resources>',
    '    <Grid Margin="5">',
    '        <Grid.Resources>',
    '            <Style TargetType="Grid">',
    '                <Setter Property="Background" Value="LightYellow"/>',
    '            </Style>',
    '        </Grid.Resources>',
    '        <Grid.RowDefinitions>',
    '            <RowDefinition Height="40"/>',
    '            <RowDefinition Height="*"/>',
    '            <RowDefinition Height="40"/>',
    '        </Grid.RowDefinitions>',
    '        <Grid Grid.Row="0">',
    '            <Grid.ColumnDefinitions>',
    '                <ColumnDefinition Width="100"/>',
    '                <ColumnDefinition Width="70"/>',
    '                <ColumnDefinition Width="*"/>',
    '            </Grid.ColumnDefinitions>',
    '            <Label Grid.Column="0"',
    '                   Content="[Command]:"',
    '                   HorizontalContentAlignment="Center"/>',
    '            <ComboBox Grid.Column="1" Name="CommandSlot">',
    '                <ComboBoxItem Content="Forest"/>',
    '                <ComboBoxItem Content="Tree"/>',
    '                <ComboBoxItem Content="Child"/>',
    '                <ComboBoxItem Content="Clone"/>',
    '            </ComboBox>',
    '            <DataGrid Grid.Column="2"',
    '                      Margin="10"',
    '                      Name="Command"',
    '                      HeadersVisibility="None">',
    '                <DataGrid.Columns>',
    '                    <DataGridTextColumn Header="Description" ',
    '                                        Width="*" ',
    '                                        Binding="{Binding Description}"/>',
    '                </DataGrid.Columns>',
    '            </DataGrid>',
    '        </Grid>',
    '        <TabControl Grid.Row="1" Name="Main">',
    '            <TabItem Header="Mode">',
    '                <Grid>',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="30"/>',
    '                        <RowDefinition Height="50"/>',
    '                        <RowDefinition Height="10"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="10"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="10"/>',
    '                        <RowDefinition Height="40"/>',
    '                    </Grid.RowDefinitions>',
    '                    <DataGrid Grid.Row="0"',
    '                              Name="OperatingSystemCaption"',
    '                              HeadersVisibility="None">',
    '                        <DataGrid.Columns>',
    '                            <DataGridTextColumn Header="Caption"',
    '                                                Width="*"',
    '                                                Binding="{Binding Caption}"/>',
    '                        </DataGrid.Columns>',
    '                    </DataGrid>',
    '                    <DataGrid Grid.Row="1" Name="OperatingSystemExtension">',
    '                        <DataGrid.Columns>',
    '                            <DataGridTextColumn Header="Version"',
    '                                                Width="80"',
    '                                                Binding="{Binding Version}"/>',
    '                            <DataGridTextColumn Header="Build"',
    '                                                Width="50"',
    '                                                Binding="{Binding Build}"/>',
    '                            <DataGridTextColumn Header="Serial"',
    '                                                Width="*"',
    '                                                Binding="{Binding Serial}"/>',
    '                            <DataGridTextColumn Header="Language"',
    '                                                Width="50"',
    '                                                Binding="{Binding Language}"/>',
    '                            <DataGridTextColumn Header="Product"',
    '                                                Width="50"',
    '                                                Binding="{Binding Product}"/>',
    '                            <DataGridTextColumn Header="Type"',
    '                                                Width="50"',
    '                                                Binding="{Binding Type}"/>',
    '                        </DataGrid.Columns>',
    '                    </DataGrid>',
    '                    <Grid Grid.Row="3" Name="ForestModeBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="50"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label Grid.Column="1"',
    '                               Content="Forest Mode"',
    '                               Style="{StaticResource LabelGray}"/>',
    '                        <ComboBox Grid.Column="2"',
    '                                  Name="ForestMode"',
    '                                  SelectedIndex="0">',
    '                            <ComboBox.ItemTemplate>',
    '                                <DataTemplate>',
    '                                    <TextBlock Text="{Binding Index}"',
    '                                               IsEnabled="{Binding Enabled}"/>',
    '                                </DataTemplate>',
    '                            </ComboBox.ItemTemplate>',
    '                        </ComboBox>',
    '                        <DataGrid Grid.Column="3"',
    '                                  Name="ForestModeExtension"',
    '                                  HeadersVisibility="None"',
    '                                  Margin="10">',
    '                            <DataGrid.Columns>',
    '                                <DataGridTextColumn Header="Name"',
    '                                                    Binding="{Binding Name}"',
    '                                                    Width="100"/>',
    '                                <DataGridTextColumn Header="DisplayName"',
    '                                                    Binding="{Binding DisplayName}"',
    '                                                    Width="*"/>',
    '                            </DataGrid.Columns>',
    '                        </DataGrid>',
    '                    </Grid>',
    '                    <Grid Grid.Row="4" Name="DomainModeBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="50"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label Grid.Column="1"',
    '                               Content="Domain Mode"',
    '                               Style="{StaticResource LabelGray}"/>',
    '                        <ComboBox Grid.Column="2"',
    '                                  Name="DomainMode"',
    '                                  SelectedIndex="0">',
    '                            <ComboBox.ItemTemplate>',
    '                                <DataTemplate>',
    '                                    <TextBlock Text="{Binding Index}"',
    '                                               IsEnabled="{Binding Enabled}"/>',
    '                                </DataTemplate>',
    '                            </ComboBox.ItemTemplate>',
    '                        </ComboBox>',
    '                        <DataGrid Grid.Column="3"',
    '                                  Name="DomainModeExtension"',
    '                                  HeadersVisibility="None"',
    '                                  Margin="10">',
    '                            <DataGrid.Columns>',
    '                                <DataGridTextColumn Header="Name"',
    '                                                    Binding="{Binding Name}"',
    '                                                    Width="100"/>',
    '                                <DataGridTextColumn Header="DisplayName"',
    '                                                    Binding="{Binding DisplayName}"',
    '                                                    Width="*"/>',
    '                            </DataGrid.Columns>',
    '                        </DataGrid>',
    '                    </Grid>',
    '                    <Grid Grid.Row="6" Name="ReplicationSourceDCBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="50"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label    Grid.Column="1"',
    '                                  Content="Replication DC"',
    '                                  Style="{StaticResource LabelGray}"/>',
    '                        <ComboBox Grid.Column="3" Name="ReplicationSourceDC"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="8" Name="SiteNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="50"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label    Grid.Column="1"',
    '                                  Content="Site Name"',
    '                                  Style="{StaticResource LabelGray}"/>',
    '                        <Image    Grid.Column="2"',
    '                                  Name="SiteNameIcon"/>',
    '                        <ComboBox Grid.Column="3"',
    '                                  Name="SiteName"/>',
    '                    </Grid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Features">',
    '                <Grid>',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="*"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Label    Grid.Row="0"',
    '                              Content="[Windows Server features to be installed]:"/>',
    '                    <DataGrid Grid.Row="1"',
    '                              Name="Feature">',
    '                        <DataGrid.Columns>',
    '                            <DataGridTextColumn Header="Type"',
    '                                                Width="60"',
    '                                                Binding="{Binding Type}"',
    '                                                CanUserSort="True"',
    '                                                IsReadOnly="True"/>',
    '                            <DataGridTextColumn Header="Name"',
    '                                                Width="*"',
    '                                                Binding="{Binding Name}"',
    '                                                CanUserSort="True"',
    '                                                IsReadOnly="True"',
    '                                                FontWeight="Bold"/>',
    '                            <DataGridTemplateColumn Header="Install" Width="40">',
    '                                <DataGridTemplateColumn.CellTemplate>',
    '                                    <DataTemplate>',
    '                                        <CheckBox IsEnabled="{Binding Enable}"',
    '                                                  IsChecked="{Binding Install}"',
    '                                                  Margin="0"',
    '                                                  Height="18"',
    '                                                  HorizontalAlignment="Left"/>',
    '                                    </DataTemplate>',
    '                                </DataGridTemplateColumn.CellTemplate>',
    '                            </DataGridTemplateColumn>',
    '                        </DataGrid.Columns>',
    '                    </DataGrid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Roles/Paths">',
    '                <Grid>',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Label Grid.Row="0" Content="[Domain controller roles]:"/>',
    '                    <Grid Grid.Row="1">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="32"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="32"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <CheckBox Grid.Column="1"',
    '                                  Name="InstallDNS"/>',
    '                        <Label    Grid.Column="2"',
    '                                  Content="Install DNS"',
    '                                  Style="{StaticResource LabelRed}"/>',
    '                        <CheckBox Grid.Column="3"',
    '                                  Name="NoGlobalCatalog"/>',
    '                        <Label    Grid.Column="4"',
    '                                  Content="No Global Catalog"',
    '                                  Style="{StaticResource LabelRed}"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="2">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="32"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="32"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <CheckBox Grid.Column="1"',
    '                                  Name="CreateDNSDelegation"/>',
    '                        <Label    Grid.Column="2"',
    '                                  Content="Create DNS Delegation"',
    '                                  Style="{StaticResource LabelRed}"/>',
    '                        <CheckBox Grid.Column="3"',
    '                                  Name="CriticalReplicationOnly"/>',
    '                        <Label    Grid.Column="4"',
    '                                  Content="Critical Replication Only"',
    '                                  Style="{StaticResource LabelRed}"/>',
    '                    </Grid>',
    '                    <Label Grid.Row="3"',
    '                           Content="[Active Directory partition target paths]:"/>',
    '                    <Grid Grid.Row="4">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Button   Grid.Column="1"',
    '                                  Name="DatabaseBrowse"',
    '                                  Content="Database"/>',
    '                        <TextBox  Grid.Column="2"',
    '                                  Name="DatabasePath"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="5">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Button   Grid.Column="1"',
    '                                  Name="SysvolBrowse"',
    '                                  Content="SysVol"/>',
    '                        <TextBox  Grid.Column="2"',
    '                                  Name="SysvolPath"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="6">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Button  Grid.Column="1"',
    '                                 Name="LogBrowse"',
    '                                 Content="Log"/>',
    '                        <TextBox Grid.Column="2"',
    '                                 Name="LogPath"/>',
    '                    </Grid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Names">',
    '                <Grid>',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="20"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Label Grid.Row="0"',
    '                           Content="[Domain Names - Necessary fields vary by command selection]:"/>',
    '                    <Grid Grid.Row="2" Name="ParentDomainNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="1"',
    '                                 Content="Parent Domain"',
    '                                 Style="{StaticResource LabelGray}"/>',
    '                        <Image   Grid.Column="2"',
    '                                 Name="ParentDomainNameIcon"/>',
    '                        <TextBox Grid.Column="3" ',
    '                                 Name="ParentDomainName"/>',
    '                    </Grid>',
    '                    <Grid   Grid.Row="3" Name="DomainNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="1"',
    '                                 Content="Domain"',
    '                                 Style="{StaticResource LabelGray}"/>',
    '                        <Image   Grid.Column="2"',
    '                                 Name="DomainNameIcon"/>',
    '                        <TextBox Grid.Column="3"',
    '                                 Name="DomainName"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="4" Name="NewDomainNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="1"',
    '                                 Content="New Domain"',
    '                                 Style="{StaticResource LabelGray}"/>',
    '                        <Image   Grid.Column="2"',
    '                                 Name="NewDomainNameIcon"/>',
    '                        <TextBox Grid.Column="3"',
    '                                 Name="NewDomainName"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="5" Name="DomainNetBiosNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="1"',
    '                                 Content="NetBIOS"',
    '                                 Style="{StaticResource LabelGray}"/>',
    '                        <Image   Grid.Column="2"',
    '                                 Name="DomainNetBIOSNameIcon"/>',
    '                        <TextBox Grid.Column="3"',
    '                                 Name="DomainNetBIOSName"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="6" Name="NewDomainNetBiosNameBox">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="120"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="25"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="1"',
    '                                 Content="New NetBIOS"',
    '                                 Style="{StaticResource LabelGray}"/>',
    '                        <Image   Grid.Column="2"',
    '                                 Name="NewDomainNetBIOSNameIcon"/>',
    '                        <TextBox Grid.Column="3"',
    '                                 Name="NewDomainNetBIOSName"/>',
    '                    </Grid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Credential">',
    '                <Grid Name="CredentialBox" IsEnabled="False">',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="*"/>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="40"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Label Grid.Row="0" Content="[Active Directory (server connection + credential) details]:"/>',
    '                    <Grid Grid.Row="1">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="100"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="50"/>',
    '                            <ColumnDefinition Width="125"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label   Grid.Column="0" Content="[Server]:"/>',
    '                        <TextBox Grid.Column="1" Name="ServerText"/>',
    '                        <TextBox Grid.Column="2"',
    '                                         Name="ServerPort"',
    '                                         TextAlignment="Left"',
    '                                         IsEnabled="True">389</TextBox>',
    '                        <Button Grid.Column="3" Name="ServerConnect" Content="Connect"/>',
    '                    </Grid>',
    '                    <DataGrid Grid.Row="2" Name="ServerList">',
    '                        <DataGrid.Columns>',
    '                            <DataGridTextColumn Header="IpAddress"',
    '                                            Width="140"',
    '                                            Binding="{Binding IPAddress}"/>',
    '                            <DataGridTextColumn Header="Hostname"',
    '                                            Width="200"',
    '                                            Binding="{Binding HostName}"/>',
    '                            <DataGridTextColumn Header="NetBIOS"',
    '                                            Width="140"',
    '                                            Binding="{Binding NetBios}"/>',
    '                        </DataGrid.Columns>',
    '                    </DataGrid>',
    '                    <Grid Grid.Row="3">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="100"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label Grid.Column="0" Content="[Credential]:"/>',
    '                        <TextBox Grid.Column="1" Name="CredentialText"/>',
    '                    </Grid>',
    '                    <Grid Grid.Row="4">',
    '                        <Grid.ColumnDefinitions>',
    '                            <ColumnDefinition Width="100"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                            <ColumnDefinition Width="100"/>',
    '                            <ColumnDefinition Width="*"/>',
    '                        </Grid.ColumnDefinitions>',
    '                        <Label       Grid.Column="0" Content="[Password]:"/>',
    '                        <PasswordBox Grid.Column="1" Name="CredentialPassword"/>',
    '                        <Label       Grid.Column="2" Content="[Confirm]:"/>',
    '                        <PasswordBox Grid.Column="3" Name="CredentialConfirm"/>',
    '                    </Grid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Connection/Dsrm Key">',
    '                <Grid Grid.Row="0">',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="*"/>',
    '                        <RowDefinition Height="120"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Grid Grid.Row="0" Name="ConnectionBox" IsEnabled="False">',
    '                        <Grid.RowDefinitions>',
    '                            <RowDefinition Height="40"/>',
    '                            <RowDefinition Height="50"/>',
    '                            <RowDefinition Height="*"/>',
    '                        </Grid.RowDefinitions>',
    '                        <Label Grid.Row="0" Content="[Connection Details]:"/>',
    '                        <DataGrid Grid.Row="1" Name="Connection">',
    '                            <DataGrid.Columns>',
    '                                <DataGridTextColumn Header="IpAddress" Binding="{Binding IpAddress}" Width="120"/>',
    '                                <DataGridTextColumn Header="DnsName"   Binding="{Binding DnsName}"   Width="200"/>',
    '                                <DataGridTextColumn Header="Domain"    Binding="{Binding Domain}"    Width="*"/>',
    '                            </DataGrid.Columns>',
    '                        </DataGrid>',
    '                        <DataGrid Grid.Row="2" Name="ConnectionExtension">',
    '                            <DataGrid.Columns>',
    '                                <DataGridTextColumn Header="Name"  Binding="{Binding Name}"  Width="100"/>',
    '                                <DataGridTextColumn Header="Value" Binding="{Binding Value}" Width="*"/>',
    '                            </DataGrid.Columns>',
    '                        </DataGrid>',
    '                    </Grid>',
    '                    <Grid Grid.Row="1">',
    '                        <Grid.RowDefinitions>',
    '                            <RowDefinition Height="40"/>',
    '                            <RowDefinition Height="40"/>',
    '                            <RowDefinition Height="40"/>',
    '                        </Grid.RowDefinitions>',
    '                        <Label Grid.Row="0" Content="[Domain Services Restore Mode Key]:"/>',
    '                        <Grid Grid.Row="1">',
    '                            <Grid.ColumnDefinitions>',
    '                                <ColumnDefinition Width="25"/>',
    '                                <ColumnDefinition Width="100"/>',
    '                                <ColumnDefinition Width="25"/>',
    '                                <ColumnDefinition Width="*"/>',
    '                                <ColumnDefinition Width="25"/>',
    '                            </Grid.ColumnDefinitions>',
    '                            <Label Grid.Column="1"',
    '                               Content="Password"',
    '                               Style="{StaticResource LabelGray}"/>',
    '                            <Image Grid.Column="2"',
    '                               Name="SafeModeAdministratorPasswordIcon"/>',
    '                            <PasswordBox Grid.Column="3"',
    '                                     Name="SafeModeAdministratorPassword"/>',
    '                        </Grid>',
    '                        <Grid Grid.Row="2">',
    '                            <Grid.ColumnDefinitions>',
    '                                <ColumnDefinition Width="25"/>',
    '                                <ColumnDefinition Width="100"/>',
    '                                <ColumnDefinition Width="25"/>',
    '                                <ColumnDefinition Width="*"/>',
    '                                <ColumnDefinition Width="25"/>',
    '                            </Grid.ColumnDefinitions>',
    '                            <Label Grid.Column="1"',
    '                               Content="Confirm"',
    '                               Style="{StaticResource LabelGray}"/>',
    '                            <Image Grid.Column="2"',
    '                               Name="ConfirmIcon"/>',
    '                            <PasswordBox Grid.Column="3"',
    '                                     Name="Confirm"/>',
    '                        </Grid>',
    '                    </Grid>',
    '                </Grid>',
    '            </TabItem>',
    '            <TabItem Header="Summary">',
    '                <Grid>',
    '                    <Grid.RowDefinitions>',
    '                        <RowDefinition Height="40"/>',
    '                        <RowDefinition Height="*"/>',
    '                    </Grid.RowDefinitions>',
    '                    <Label Grid.Row="0" Content="[Issues preventing promotion]:"/>',
    '                    <DataGrid Grid.Row="1" Name="Summary">',
    '                        <DataGrid.Columns>',
    '                            <DataGridTextColumn Header="Name"',
    '                                                Binding="{Binding Name}"',
    '                                                Width="150"/>',
    '                            <DataGridTextColumn Header="Reason"',
    '                                                Binding="{Binding Reason}"',
    '                                                Width="*"/>',
    '                        </DataGrid.Columns>',
    '                    </DataGrid>',
    '                </Grid>',
    '            </TabItem>',
    '        </TabControl>',
    '        <Grid Grid.Row="2">',
    '            <Grid.ColumnDefinitions>',
    '                <ColumnDefinition Width="*"/>',
    '                <ColumnDefinition Width="*"/>',
    '                <ColumnDefinition Width="*"/>',
    '                <ColumnDefinition Width="*"/>',
    '            </Grid.ColumnDefinitions>',
    '            <Button Grid.Column="0"',
    '                    Name="Start"',
    '                    Content="_Start"/>',
    '            <Button Grid.Column="1"',
    '                    Name="Test"',
    '                    Content="_Test"/>',
    '            <Button Grid.Column="2"',
    '                    Name="Save"',
    '                    Content="Sa_ve"/>',
    '            <Button Grid.Column="3"',
    '                    Name="Load"',
    '                    Content="_Load"/>',
    '        </Grid>',
    '    </Grid>',
    '</Window>' -join "`n")
}
