$TypeDefinition = '// slightly modified version of https://rosettacode.org/wiki/Pi#C#',
'using System;',
'using System.Numerics;',
'',
'namespace Calculate',
'{',
'    public class Pi',
'    {',
'        private readonly BigInteger FOUR  = new BigInteger(4);',
'        private readonly BigInteger SEVEN = new BigInteger(7);',
'        private readonly BigInteger TEN   = new BigInteger(10);',
'        private readonly BigInteger THREE = new BigInteger(3);',
'        private readonly BigInteger TWO   = new BigInteger(2);',
'        ',
'        private BigInteger k = BigInteger.One;',
'        private BigInteger l = new BigInteger(3);',
'        private BigInteger n = new BigInteger(3);',
'        private BigInteger q = BigInteger.One;',
'        private BigInteger r = BigInteger.Zero;',
'        private BigInteger t = BigInteger.One;',
'',
'        public bool Cancel { get; set; }',
'        ',
'        public void Execute()',
'        {',
'            BigInteger nn, nr;',
'            bool first = true;',
'',
'            while (!Cancel)',
'            {',
'                if (Console.KeyAvailable)',
'                {',
'                    Console.ReadKey(intercept: true);',
'                    Cancel = true;',
'                    Console.Write("\n\n");',
'                    break;',
'                }',
'',
'                if ((FOUR * q + r - t).CompareTo(n * t) == -1)',
'                {',
'                    Console.Write(n);',
'                    if (first)',
'                    {',
'                        Console.Write(".");',
'                        first = false;',
'                    }',
'',
'                    nr = TEN * (r - (n * t));',
'                    n  = TEN * (THREE * q + r)/t - (TEN * n);',
'                    q *= TEN;',
'                    r  = nr;',
'                }',
'                else',
'                {',
'                    nr  = (TWO * q + r) * l;',
'                    nn  = (q * (SEVEN * k) + TWO + r * l)/(t * l);',
'                    q  *= k;',
'                    t  *= l;',
'                    l  += TWO;',
'                    k  += BigInteger.One;',
'                    n   = nn;',
'                    r   = nr;',
'                }',
'            }',
'        }',
'    }',
'}' -join "`n"

Add-Type -ReferencedAssemblies "System","System.Numerics" -TypeDefinition $TypeDefinition

$Pi = [Calculate.Pi]::New()
$Pi.Execute()
